server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/s-pay-mall?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=America/New_York&useSSL=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 微信公众号对接
weixin:
  config:
    originalid: gh_e5d6b1e312f0
    token: b8b6
    app-id: wx92b256692c2cdc80
    app-secret: a80a49f144857e019fcf145520e1b727
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000150643663
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6ZKQYIRitnUs4CwPk1xkz/BxnlzVEVQvzs1S9pJHP7eNOu23AsXGXy0iTcqObUICQpnaWJJNvVT9qaHA1tKjZxgb2dRNScpE/58NzTo8O8MCIi81tS9ZL1W4OfOfaiwc0HGbVtaiMy/OztjlgfDChALvYb7CDiC26ycFLLsoP8ndLD+wLYbBp5SJGIX6EXQvrPYl7zMJzhbzzQJYpm1KA3zoIuVhzxH/9THJYv8JwGpkP+5GZ/AxMBFzVkgo6xwGt2X+xTvJYmCwEAbaiEpKPuMIobCuH41Os2+mNnRcCG5KJMf/9U9wpwovan8GVAus7xhlgKjYeonLBkh5WC+ghAgMBAAECggEAUJn8q8KEHW+Le2yn/mlVqLk4v0MP8cClLnk6B9gGhdflF8LNLyqMaIurkrdcMGmbbvHNDhg6+UXv6l/HRjIdYi7UC/eMp3aLgQsD5fTuwBMz7tgluUG2JYzhzroMuOCt+MbfYULw5BG+DNSb8zFBBh5/HJUPy5Ez1TYxtAVDs6jz5/G/atH30624vvfLAftGwnwqSKU87DjK/jrV95+vz1bDw/K2wSvZXdxGjSJNC+L2TrFc5xK/9KoPBx76QqJ6285mAfaCE9ZqAURvyVS2NeFwJAPzj+pHt0ue4FqGs/uoNNW0eOO+B24y9w/d+WkSbiyEvkrhQBQ69JyCcGBI0QKBgQD1GRh1Jf4c+gyYes9E6AwUNs6bajh5gkrfYV87C0fTWqjLdlg7RH/CcG+BeCypyB6+/8bUOVnQQcbg+j0P/ACypR8o7yEuXzs8YAEQfPtgdjxSME+zQZefzMQ8KwvRIhYtczvUOHimWJmfkT/ax842KuTjQgJlM+dxkqZmD/lc5wKBgQDCrxREmB/yobHomaJG9rMY5RPeYThQJ9jYOyU2GKytXyusJ0u8NKD211qSDWhU593FBOZDY76JAgUVX7Q19TzrNwni/HTED7BHDGdmm5Ctip7jwuMPDrT/ICAmGsJZgjMHWmpvIgpfhYg4J2JipyFzM/Abm25Qp8NlaGBmmxqptwKBgQDha0JORDIRjnxVJOZKdqzdTob481mbj5SzHAgM8tQNdB04e9CsOdTTDLvRNKjHQjHc8rt4ZoLPAiAavKu6bshphWpCKKS41IdTgOyZsIk176iM4rf6osIEC70TpXeJ0bLZ/FizV3jHbUdlNZ6n5gonUY4P4Z74WyNrFjiKN/jdUwKBgFY4thA/E38gz6tFR5KINf+jjO4jPo55Z1c0sqFHwkoyaSQgbzFWWaeY7vraR0e7PQPBzL0x0rPZGilCLozrJOTDhnRp/MjMbfS5cJ4H7cZ+KyqSKH+FsvF+594YYdTEjhcGmzbG67Msb4z3HGK2xGDCMuf3KZ88/ZPO60rmDKP3AoGBAPUIOQGaiFBNHGpO3ZUddXB/J7jab8XqDRYCaPdQaGeSqBIXP9IUQkxmvXhVOLINuTYHpXv3+II5eo51bsbprn3S/G/DIAuIZiIkuFRBadls7p3P+aCED4d10F7bzXJPKpGkDbEKxKis6qRtIni7Tgikiak5uSLxTAe7RUB+vsY/
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1ag+XKjGYrsxrmvkPWEaKf1xkPyv8TmYkCWIB0YERsJqjBAbZgxTBroq3J1BrZPgPeHjH7YhMbUGZQ48nwnvqc3QEPAJLlEWK6KAY8Uw6iHsEQEQDLc35Lq9BskaMSC981G5QAPmWz1vSz2qInB5HWxk7Ql7eDh+qnM16F92gkjJ2LfXNF5sLr/nYviUW2bMZEUDMC3YPHxvWRjrFg44zx/S1GVveUAH/B/YNFWzI8uEv9UUKBioCNWMSs0b4bjlcIaycUCviuQs/AqbFm6qHQD4v6RJd5Nhi3jvUwPSxq35cF2wXeCLSLKvJ8wdpRSGD8grc2SD+amknfvBAUP7aQIDAQAB
  notify_url: http://webnet.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://github.com/xuefeng16513/s-pay-mall
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml