server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/s-pay-mall?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver




# 微信公众号对接
weixin:
  config:
    originalid: gh_db9aec6fcfc2
    token: b8b6
    accessToken: 94_L18wLaPdzQfM2ExFrkOKJSVE6yg6DEIPHzaD20E2UGxTWiKH2s8zb7lO1k5r2LsN_JrB8F1YUyEro9DuH6_THpt-eh4vToBoIVncBzXAclLcgnkPuvAzwuQn0pQCSEbACAGWI  # ⚠️ 使用你自己的 access_token（有效期2小时）



# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml