server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/s-pay-mall?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/s-pay-mall?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver




# 微信公众号对接
weixin:
  config:
    originalid: gh_e5d6b1e312f0
    token: b8b6
    app-id: wx92b256692c2cdc80
    app-secret: a80a49f144857e019fcf145520e1b727
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y



# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml